<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gas Engineer Website</title>
    <!-- Add your CSS file here if you have one -->
</head>
<body>
    <header>
        <h1>Welcome to Gas Engineer Services</h1>
        <nav>
            <ul>
                <li><a href="#about">About Us</a></li>
                <li><a href="#services">Services</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>

    <section id="about">
        <h2>About Us</h2>
        <p>We are a team of experienced and certified gas engineers dedicated to providing high-quality gas-related services.</p>
    </section>

    <section id="services">
        <h2>Our Services</h2>
        <ul>
            <li>Gas Appliance Installation</li>
            <li>Gas Safety Inspections</li>
            <li>Gas Leak Detection and Repair</li>
            <li>Boiler Installation and Repair</li>
            <li>Heating System Maintenance</li>
        </ul>
    </section>

    <section id="contact">
        <h2>Contact Us</h2>
        <p>If you need our services or have any questions, please don't hesitate to get in touch.</p>
        <p>Email: <a href="mailto:info@gasengineer.com">info@gasengineer.com</a></p>
        <p>Phone: <a href="tel:+1234567890">123-456-7890</a></p>
    </section>

    <footer>
        <p>&copy; 2023 Gas Engineer Services</p>
    </footer>

    <!-- Add your JavaScript file here if you have one -->
<style>
/* Reset some default browser styles */
body, h1, h2, p, ul, li {
    margin: 0;
    padding: 0;
}

/* Apply a background color and text color to the body */
body {
    background-color: #f4f4f4;
    color: #333;
    font-family: Arial, sans-serif;
    line-height: 1.6;
    margin: 0;
    padding: 0;
}

/* Style the header section */
header {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 20px 0;
}

header h1 {
    font-size: 2rem;
}

header nav ul {
    list-style: none;
}

header nav ul li {
    display: inline;
    margin-right: 20px;
}

header nav ul li a {
    text-decoration: none;
    color: #fff;
}

/* Style the sections */
section {
    padding: 20px;
    margin: 20px;
    background-color: #fff;
    border-radius: 5px;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
}

/* Style the footer */
footer {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 10px 0;
}

/* Add additional styles as needed */


</style>
</body>
</html>
